const handlebars = require('handlebars');

const BASE_LAYOUT = `
  <div class="page-header">
    {{{header}}}
  </div>
  <div class="main-content">
    {{{content}}}
  </div>
  <div class="page-footer">
    {{{footer}}}
    <div class="page-number-container">
      Page <span class="pageNumber"></span> of <span class="totalPages"></span>
    </div>
  </div>
`;

const TEMPLATES = {
  resume: {
    header: '<h1>{{title}}</h1><p>{{email}} | {{phone}}</p>',
    footer: '<hr/><p>Generated by Rich Text PDF Writer</p>',
    styles: `
      .main-content { padding: 20px; }
      h1 { color: #2c3e50; border-bottom: 2px solid #2c3e50; }
    `
  },
  report: {
    header: '<div style="text-align: center;"><h2>{{title}}</h2><p>Confidential Report</p></div>',
    footer: '<div style="text-align: right;">{{date}}</div>',
    styles: `
      .main-content { padding: 40px; }
      h2 { text-transform: uppercase; }
    `
  },
  notes: {
    header: '<h3>Study Notes: {{title}}</h3>',
    footer: '<p>Category: {{category}}</p>',
    styles: `
      .main-content { padding: 30px; border: 1px solid #eee; }
    `
  },
  invoice: {
    header: '<div style="display: flex; justify-content: space-between;"><h1>INVOICE</h1><div>{{companyName}}</div></div>',
    footer: '<p>Thank you for your business!</p>',
    styles: `
      .main-content { padding: 50px; }
      .invoice-info { margin-bottom: 30px; }
    `
  }
};

/**
 * Applies a template to the content and metadata.
 * @param {string} contentHTML - The main body content in HTML
 * @param {string} templateName - The name of the template to use
 * @param {Object} metadata - Metadata for headers/footers
 * @returns {Object} - { html, headerTemplate, footerTemplate }
 */
function applyTemplate(contentHTML, templateName, metadata = {}) {
  const template = TEMPLATES[templateName] || { header: '', footer: '', styles: '' };
  
  const headerFn = handlebars.compile(template.header);
  const footerFn = handlebars.compile(template.footer);
  
  const headerHTML = headerFn(metadata);
  const footerHTML = footerFn(metadata);
  
  const fullHTML = `
    <style>
      ${template.styles || ''}
      .page-header { width: 100%; }
      .page-footer { width: 100%; font-size: 10pt; color: #666; }
      .page-number-container { text-align: center; margin-top: 5px; }
    </style>
    <div class="template-wrapper">
      ${contentHTML}
    </div>
  `;

  return {
    html: fullHTML,
    headerTemplate: `<div style="font-size: 10px; width: 100%; text-align: center; border-bottom: 1px solid #eee; padding-bottom: 5px;">${headerHTML}</div>`,
    footerTemplate: `<div style="font-size: 10px; width: 100%; text-align: center; border-top: 1px solid #eee; padding-top: 5px;">${footerHTML} <span class="pageNumber"></span> / <span class="totalPages"></span></div>`
  };
}

module.exports = { applyTemplate, TEMPLATES };
